name: cgpacalculator
description: A new Flutter project.
publish_to: 'none'
version: 1.0.11+11

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11
  path_provider: ^2.0.8
  provider: ^6.0.2
  moor_flutter: ^4.0.0
  google_sign_in: ^5.2.1
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  marquee: ^2.2.0
  page_transition: "^2.0.4"
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  moor_generator: ^4.6.0+1
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/launcher/icon.png"
  image_path_ios: "assets/launcher/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 100
