name: cgpacalculator
description: Journaling and Analysing Courses and CGPA Made Easy
publish_to: 'none'
version: 1.0.15+15

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  provider: ^6.1.1
  drift_sqflite: ^2.0.1
  drift: ^2.15.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  marquee: ^2.2.3
  page_transition: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  sqlite3_flutter_libs:

dev_dependencies:
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

dependency_overrides:
  watcher: ^1.1.0
  fading_edge_scrollview: ^4.1.1
flutter_icons:
  image_path_android: 'assets/launcher/icon.png'
  image_path_ios: 'assets/launcher/icon.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 100
